FROM debian:bullseye
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y redis-server && rm -rf /var/lib/apt/lists/*
EXPOSE 6379
CMD ["redis-server", "/etc/redis/redis.conf", "--daemonize", "no"]