user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # SSL and other configurations

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip and other settings
    gzip on;

    # Your virtual host configuration

    server {
        listen 80;
        server_name localhost;

        # Redirect all HTTP traffic to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        server_name 42.fr  default_server;
        ssl_certificate /etc/nginx/ssl/certificate.crt;          # Path to the public certificate
        ssl_certificate_key /etc/nginx/ssl/private.key;          # Path to the private key
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256';
        
        root /usr/share/nginx/html;
        index index.php index2.html;

        
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;  # Backend PHP-FPM server listening on UNIX socket
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location /wp-admin {
            try_files $uri $uri/ /wp-admin/index.php?$args;
        }
        location /wp-login.php {
            return 404;
        }
        location /secretgarden {
            rewrite ^/secretgarden$ /wp-login.php last;
        }
    }
    server {
        listen 443 ssl;#listen 443 ssl default_server, when client connects to the server, it will use the certificate of the default_server;
        #when client connects to the server, using ip instead of domain name, it will be served by the default_server;
        #to make a domain name work, you need to add it to /etc/hosts and here
        server_name login.42.fr;
        ssl_certificate /etc/nginx/ssl/certificate.crt;          # Path to the public certificate
        ssl_certificate_key /etc/nginx/ssl/private.key;          # Path to the private key
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256';
        
        root /usr/share/nginx/html;
        index wp-login.php;

        
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;  # Backend PHP-FPM server listening on UNIX socket
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location /wp-admin {
            try_files $uri $uri/ /wp-admin/index.php?$args;
        }
        location /wp-login.php {
            return 404;
        }
        location /secretgarden {
            rewrite ^/secretgarden$ /wp-login.php last;
        }
    }
}
    

